INHERIT: active-handout.yml
site_name: DesSoft - Design de Software
theme:
  name: active-handout-theme
  locale: pt_BR
nav:
- Home: index.md
- Dicas:
  - Buscando ajuda: buscando-ajuda/index.md
- Conteúdo:
  - Introdução: introducao/handout.md
  - Funções: funcao/handout.md
  - Entrada e saída: input/handout.md
  - Desvios condicionais (if): if/handout.md
  - Laços de Repetição (while): while/handout.md
  - Armazenamento de dados em listas: lista/handout.md
  - Iterando em coleções com "for": for/handout.md
  - Armazenamento em dicionários: dicionario/handout.md
  - Strings e Fatiamento: string/handout.md
  - Armazenamento permanente em arquivos: arquivo/handout.md
  - PyGame: pygame/handout.md
- Tutoriais:
  - Usando o terminal (MacOS): terminal-macos/index.md
  - Usando o terminal (Windows): terminal-win/index.md
  - Controle de versões com Git: git/index.md
extra:
  custom_variables:
    pl_root: https://us.prairielearn.com/pl/course_instance/206137
    pl_funcao: https://us.prairielearn.com/pl/course_instance/206137/assessment/2634296
    pl_input: https://us.prairielearn.com/pl/course_instance/206137/assessment/2634298
    pl_if: https://us.prairielearn.com/pl/course_instance/206137/assessment/2634297
    pl_while: https://us.prairielearn.com/pl/course_instance/206137/assessment/2634317
    pl_list: https://us.prairielearn.com/pl/course_instance/206137/assessment/2634300
    pl_for: https://us.prairielearn.com/pl/course_instance/206137/assessment/2634295
    pl_dict: https://us.prairielearn.com/pl/course_instance/206137/assessment/2634284
    pl_string: https://us.prairielearn.com/pl/course_instance/206137/assessment/2634316
    pl_files: https://us.prairielearn.com/pl/course_instance/206137/assessment/2634294
    pl_classes: https://us.prairielearn.com/pl/course_instance/206137/assessment/2634283
extra_javascript:
- js/tabs.js
- js/termynal.js
- js/custom.js
extra_css:
- css/termynal.css
- css/custom.css
